### ISSUE TITLE
Doesn't work on iOs

### ISSUE THREAD

**Issue by ivy-mihai** [react-native-community/segmented-control#102]
# Bug report

## Summary

The package doesn't work on iOs. The main example from Git is working perfectly on Android, but on iOS I receie this error"View config not found for name RNC Segmented Control".
## Environment info

I am using Expo.

`react-native info` output:

```bash
# paste it here
```

Library version: x.x.x

## Steps to reproduce

1. cut example code from git
2. copy example code in the component where I want to use the component
3. I am trying to open the screen that contains the segmenet-control component
4.  is working perfectly on Android, but on iOS I see the red screen with this error message "View config not found for name RNC Segmented Control".

Describe what you expected to happen:

1. to see the segment-control component behaving the same on android and iOs

## Reproducible sample code

I've created a Snack here. Try to open the app using an iOs phone. https://snack.expo.io/@ivy.mihai/94f0cf

**Comment by shireeshMs** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-06-27 at 02 44 30](https://user-images.githubusercontent.com/37240061/85901804-3112c780-b820-11ea-9903-81bc263f0939.png)

![Screenshot_1593206072](https://user-images.githubusercontent.com/37240061/85901813-35d77b80-b820-11ea-9628-eb0a0879232c.png)

I am facing same issue, any solution

**Comment by exotexot** [comment]
Looks like your forgot to do a pod install in the ios directory

**Comment by Naturalclar** [comment]
@ivy-mihai 
Have you tried running `npx pod-install` in your project? for iOS modules, installing its dependency via cocoapods is required.

**Comment by ivy-mihai** [comment]
> @ivy-mihai
> Have you tried running `npx pod-install` in your project? for iOS modules, installing its dependency via cocoapods is required.

I am using Windows. I cannot use npx pod-install in my project, but I've tried anyway. Here is the answer: CocoaPods is only supported on darwin machines.

**Comment by Naturalclar** [comment]
@ivy-mihai thanks for the reply! And sorry, i missed the part about expo.

Could you tell me which expo sdk version you're using?

This package will only work on iOS for expo sdk 38 and beyond.

**Comment by ivy-mihai** [comment]
> @ivy-mihai thanks for the reply! And sorry, i missed the part about expo.
> 
> Could you tell me which expo sdk version you're using?
> 
> This package will only work on iOS for expo sdk 38 and beyond.

Not a problem! Thank you for your answer. I use SDK 38.
