### ISSUE TITLE
RNCSegmentedControl was not found ?!

### ISSUE THREAD

**Issue by mertct11** [react-native-community/segmented-control#113]
greetings to everyone,

I'm working on a project. The project uses react native with expo and uses the segmented control component of the community.

The problem is that I do not encounter any problems when I compile with expo application on my android device, but when I compile with my ios device from expo application, I encounter the following screenshot. I compared the js files (import SegmentedControl from '../../js';) that you imported in your sample code in github one by one and imported the innovations into my own module. however, the error has not changed. I wonder where am I missing? can you help me?

ios ERROR! ? 
![WhatsApp Image 2020-07-25 at 14 23 16](https://user-images.githubusercontent.com/54515536/88456050-49a7e900-ce83-11ea-9b6e-689ed95fad66.jpeg)

android :

![WhatsApp Image 2020-07-25 at 14 24 09](https://user-images.githubusercontent.com/54515536/88456064-57f60500-ce83-11ea-8b2f-16005549635b.jpeg)

**Comment by mertct11** [comment]
anyone else?

**Comment by andresd** [comment]
I have the same problem, any ideas?

**Comment by amsimoes** [comment]
Same happening to me, only in iOs (using EXPO sdk 37)

**Comment by markwindsorr** [comment]
Same Issue

**Comment by Naturalclar** [comment]
For expo users, please make sure that you are using expo sdk 38 or above.
For expo users using expo 37 or below, please use the `SegmentedControlIOS` component from react-native.
For non-expo users, please make sure you run `npx pod-install` after installing this package.

**Comment by thiskevinwang** [comment]
Hi! Are there possibly any additional steps to resolve this when using `expo ~45.0.5` & `expo start --dev-client`?

**Comment by nestorLanex** [comment]
I'm using expo 44 but i get this error as well.

**Comment by Engazan** [comment]
if u using EXPO, for example SDK 49 like me you need to use "development" client for this 

how ? 
edit your "eas.json" file and add something like this to build  ( important is only `` "developmentClient": true,`` )
```
"development": {
      "channel": "development",
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "resourceClass": "m-medium"
      }
    },
``` 
    
then you need build your own Expo Go client with command ``npx eas build --profile=development``, wait few mins around 5, then download and install your build on your device 

then run ``npx expo start --dev-client``

**Comment by omgcx1222** [comment]
> I'm using expo 44 but i get this error as well.

After you `npm install --save @react-native-segmented-control/segmented-control`, you need to re-run `npx expo run:ios` for `SegmentedControl` to take effect
