### ISSUE TITLE
Changing of font size

### ISSUE THREAD

**Issue by starikovm** [react-native-community/segmented-control#59]
**Is it possible to change font size of text in segmented control element?**
Question says it all, I am trying to apply font size to the element but seems like nothing changes i nthe size of the text. Is it possible now to change it somehow?
Thanks for help in advance and thanks for cool component!

**Comment by Naturalclar** [comment]
I'll look into it!

**Comment by Naturalclar** [comment]
@starikovm I've just released v1.5.0 with `fontSize` prop that can change the fontSize :tada:
