### ISSUE TITLE
Changing of font family

### ISSUE THREAD

**Issue by kesha-antonov** [react-native-community/segmented-control#85]
# Feature request

Hi!

Thanks for awesome component!

Is it possible to change font family of text in segmented control element?

**Comment by Naturalclar** [comment]
@kesha-antonov Thanks for the feature request!
Unfortunately, currently it's not possible to change the font family of the segmented control text.

It's definitely a nice feature to have, but I don't have the bandwidth to work on it at the moment.

PRs are always welcome :+1:

**Comment by kesha-antonov** [comment]
@Naturalclar thanks for feedback!

**Comment by arjndr** [comment]
@Naturalclar I've opened a PR regarding this in #87

**Comment by Naturalclar** [comment]
I've released v2.0.0 with font family support, thanks to @arjndr :tada:
There's some breaking change in the props, so read the release note for the changes.
