### ISSUE TITLE
Android version cut off when last element is selected

### ISSUE THREAD

**Issue by thomaschaaf** [react-native-community/segmented-control#92]
# Bug report

## Summary

It seems like the right side is cut off on android since version 1.6.0 if the last item is selected.

### Version 2.0.0
First Item:
<img width="490" alt="Screenshot 2020-05-30 19 27 43" src="https://user-images.githubusercontent.com/893393/83335242-b94a8f00-a2ab-11ea-8e8b-a2af68420ddd.png">

Last Item:
<img width="512" alt="Screenshot 2020-05-30 19 06 08" src="https://user-images.githubusercontent.com/893393/83334818-5ce67000-a2a9-11ea-9ad7-084c6726f3a1.png">

---

### Version 1.5.0
<img width="512" alt="Screenshot 2020-05-30 19 21 25" src="https://user-images.githubusercontent.com/893393/83335119-c87d0d00-a2aa-11ea-997c-3fb7aa551f15.png">

## Environment info

Library version: 1.60, 1.6.1 & 2.0.0

## Steps to reproduce

Install in emulator or on device. Compare it with version 1.4.0 and there is it pretty.

## Reproducible sample code

```
<View style={{margin: 10}}>
        <SegmentedControl
          style={{margin: 10}}
          selectedIndex={1}
          values={['Photos', 'Settings']}
        />
      </View>
```

**Comment by AndriiBoiko** [comment]
The same issue ...
<img width="187" alt="Screenshot 2020-06-01 at 17 11 41" src="https://user-images.githubusercontent.com/50368724/83417665-1ae53780-a42b-11ea-803a-84334f508349.png">

**Comment by Naturalclar** [comment]
Sorry about the issue!
I'll find time this weekend to try to fix it
